name: DropMultiplier
version: 1.0.0
description: DropMultiplier allows to multiply the amount of drops of some blocks.
author: Berg Lucas
website: https://github.com/BergLucas/DropMultiplier

main: berg.lucas.dropmultiplier.DropMultiplier
api-version: 1.17

commands:
  dropmultiplier:
    description: Displays info about the plugin.
    usage: <usage> /dropmultiplier (reload)
    permission: dropmultiplier